apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: eks-sample-app
  labels:
    app: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: postgres-root-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: postgres-root-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config
              key: postgres-db

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: eks-sample-app
spec:
  selector:
    app: postgres-db
  ports:
  - port: 5432
    targetPort: 5432
