apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: eks-sample-app
data:
  postgres-db: postgres
  flask-app: app.py
  flask-env: development
  database-uri: postgresql://postgres:sheetal@postgres-db-service.default.svc.cluster.local/postgres
