apiVersion: v1
kind: Pod 
metadata:
  name: jhooq-pod
  labels:
    name: jhooq-pod
spec:
  containers:
  - name: jhooq-pod
    image: rahulwagh17/kubernetes:jhooq-k8s-springboot
    ports:
    - containerPort: 8080
      name: www
    volumeMounts:
    - name: www-persistent-storage
      mountPath: /home/deq/kubernetes/pv-pvc-sc
  volumes:
    - name: www-persistent-storage
      persistentVolumeClaim: 
        claimName: jhooq-pvc 
   
    

---